host: localhost:8080
info:
  contact: {}
  description: rtp 的云端系统
  title: rtp cloud
paths:
  /index:
    get:
      description: none
      produces:
      - application/json
      responses:
        "200":
          description: hsdf
          schema:
            type: string
        "500":
          description: "no"
          schema:
            type: string
      summary: index
      tags:
      - index
swagger: "2.0"
